name: build_and_test

env:
  CONAN_REFERENCE: "darwin-toolchain/1.0.8"
  CONAN_USERNAME: "conan-burrito"
  CONAN_UPLOAD: "https://api.bintray.com/conan/conan-burrito/main"
  CONAN_STABLE_BRANCH_PATTERN: "release/*"

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install conan
        run:  pip install conan conan_package_tools
      - name: Build
        run: python .ci/build-${{ matrix.os }}.py

